### ISSUE TITLE
campaign KO

### ISSUE THREAD

**Issue by DomitienAdW** [DomitienAdW/Harfang#127] opened 2018-02-19 17:55 UTC
A lot of campaign show are blocked…

On the first page I've list all those:

9422
9421
9420
9412
9417
9415
9418
9419
9414
9413
9416
9407
9408
9403
9406
9411
9409
9410
9401
9402
9404
9400
9405
9393
9391
9396
9395
9397
9399
9394
9392
9398
9388
9380
9381
9379

**Comment by nfilzi** [comment] 2018-02-20 14:15
Linked to #121, currently investigating.

**Comment by nfilzi** [comment] 2018-02-24 00:24
Duplicate of #121

**Closed by nfilzi** 2018-02-24 00:24 UTC
Labels: bug
